-- phpMyAdmin SQL Dump
-- version 3.4.8
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jul 08, 2012 at 01:45 PM
-- Server version: 5.5.8
-- PHP Version: 5.3.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `xvweb2`
--

-- --------------------------------------------------------

--
-- Table structure for table `xv_auction_fields`
--

CREATE TABLE IF NOT EXISTS `xv_auction_fields` (
  `fields_id` int(11) NOT NULL AUTO_INCREMENT,
  `fields_category` varchar(255) NOT NULL,
  `fields_name` varchar(100) NOT NULL,
  `fields_search` enum('none','quick','advanced','both') NOT NULL,
  `fields_options` mediumtext NOT NULL,
  `fields_search_type` varchar(50) NOT NULL,
  `fields_type` enum('string','integer') NOT NULL,
  `fields_class` varchar(40) NOT NULL,
  `fields_priority` int(3) NOT NULL,
  `fields_add_priority` int(3) NOT NULL,
  PRIMARY KEY (`fields_id`),
  UNIQUE KEY `fields_name` (`fields_name`),
  KEY `fields_category` (`fields_category`),
  KEY `fields_search_mode` (`fields_search`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=37 ;

--
-- Dumping data for table `xv_auction_fields`
--

INSERT INTO `xv_auction_fields` (`fields_id`, `fields_category`, `fields_name`, `fields_search`, `fields_options`, `fields_search_type`, `fields_type`, `fields_class`, `fields_priority`, `fields_add_priority`) VALUES
(2, '/', 'title', 'none', 'a:18:{s:7:"caption";s:8:"Tytuł: ";s:17:"quick_input_style";s:12:"width: 64px;";s:15:"quick_afer_text";s:0:"";s:17:"quick_label_style";s:12:"width: 64px;";s:20:"advanced_input_style";s:12:"width: 64px;";s:18:"advanced_afer_text";s:0:"";s:20:"advanced_label_style";s:12:"width: 64px;";s:9:"maxlength";s:2:"50";s:10:"input_desc";s:39:"Tytul moze zawierac od 3 do 50 znaków.";s:12:"caption_desc";s:1:" ";s:5:"error";s:13:"Popraw tytuł";s:6:"filter";s:13:"/^(.){3,50}$/";s:13:"HTML5_pattern";s:9:"(.){3,50}";s:10:"input_type";s:4:"text";s:13:"detail_enable";s:1:"0";s:14:"detail_caption";s:6:"Tytuł";s:13:"detail_before";s:0:"";s:12:"detail_after";s:0:"";}', 'none', 'string', 'xvauction_fields_string', 0, 0),
(3, '/', 'description', 'none', 'a:4:{s:7:"caption";s:4:"Opis";s:10:"input_desc";s:30:"Tutaj mozesz uzywac tagow html";s:5:"error";s:17:"Zle dane podales!";s:14:"show_templates";s:1:"1";}', 'none', 'string', 'xvauction_fields_wysiwyg', 0, 0),
(5, '/', 'thumbnail', 'none', 'a:7:{s:7:"caption";s:13:"Miniaturka : ";s:10:"input_desc";s:32:"Gragika w rozdzielczosci 300x200";s:12:"caption_desc";s:1:" ";s:5:"error";s:17:"Zly format pliku!";s:12:"resize_width";s:2:"64";s:13:"resize_height";s:2:"48";s:8:"required";s:1:"0";}', 'none', 'integer', 'xvauction_fields_thumbnail', 0, 0),
(6, '/', 'buynow', 'none', 'a:16:{s:7:"Caption";s:6:"Cena :";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:4:" zł";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:2:"13";s:9:"InputDesc";s:50:"Cena w postaci 000.00 , grosze oddzielone kropką.";s:11:"CaptionDesc";s:63:"<span style="color:#ED852F; font-weight:bold;">KUP TERAZ</span>";s:5:"Error";s:71:"Złą podałeś cenę kup teraz. Grosze muszą być oddzielone KROPKĄ!";s:6:"Filter";s:51:"/^((([0-9]){0,10})|(([0-9]){0,10}(\\.)([0-9]){2}))$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -210),
(7, '/', 'auction_start', 'none', 'a:16:{s:7:"Caption";s:17:"Cena wywoławcza:";s:6:"Before";s:5:"from ";s:6:"Center";s:3:"to ";s:5:"After";s:4:" zł";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:50:"Cena w postaci 000.00 , grosze oddzielone kropką.";s:11:"CaptionDesc";s:12:"(dla aukcji)";s:5:"Error";s:71:"Złą podałeś cenę kup teraz. Grosze muszą być oddzielone KROPKĄ!";s:6:"Filter";s:51:"/^((([0-9]){0,10})|(([0-9]){0,10}(\\.)([0-9]){2}))$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -220),
(8, '/', 'auction_min', 'none', 'a:16:{s:7:"Caption";s:16:"Cena minimalna :";s:6:"Before";s:5:"from ";s:6:"Center";s:3:"to ";s:5:"After";s:2:" $";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:50:"Cena w postaci 000.00 , grosze oddzielone kropką.";s:11:"CaptionDesc";s:12:"(dla aukcji)";s:5:"Error";s:17:"Zle dane podales!";s:6:"Filter";s:51:"/^((([0-9]){0,10})|(([0-9]){0,10}(\\.)([0-9]){2}))$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -230),
(9, '/', 'dutch_start', 'none', 'a:16:{s:7:"Caption";s:16:"Cena startowa : ";s:6:"Before";s:5:"from ";s:6:"Center";s:3:"to ";s:5:"After";s:2:" $";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:50:"Cena w postaci 000.00 , grosze oddzielone kropką.";s:11:"CaptionDesc";s:26:"(dla aukcji holenderskiej)";s:5:"Error";s:71:"Złą podałeś cenę kup teraz. Grosze muszą być oddzielone KROPKĄ!";s:6:"Filter";s:51:"/^((([0-9]){0,10})|(([0-9]){0,10}(\\.)([0-9]){2}))$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -240),
(10, '/', 'dutch_min', 'none', 'a:16:{s:7:"Caption";s:16:"Cena minimalna :";s:6:"Before";s:4:"od  ";s:6:"Center";s:3:"do ";s:5:"After";s:4:" zł";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:50:"Cena w postaci 000.00 , grosze oddzielone kropką.";s:11:"CaptionDesc";s:26:"(dla aukcji holenderskiej)";s:5:"Error";s:71:"Złą podałeś cenę kup teraz. Grosze muszą być oddzielone KROPKĄ!";s:6:"Filter";s:51:"/^((([0-9]){0,10})|(([0-9]){0,10}(\\.)([0-9]){2}))$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -250),
(12, '/', 'type', 'none', 'a:12:{s:7:"caption";s:13:"Typ aukcji : ";s:18:"quick_select_style";s:12:"width: 64px;";s:21:"advanced_select_style";s:12:"width: 64px;";s:17:"quick_label_style";s:12:"width: 64px;";s:20:"advanced_label_style";s:12:"width: 64px;";s:7:"options";s:57:"Kup teraz\r\nAukcja\r\nAukcja + Kup Teraz\r\nAukcja holenderska";s:18:"quick_option_empty";s:6:"&nbsp;";s:21:"advanced_option_empty";s:6:"&nbsp;";s:10:"input_desc";s:42:"Tytuł może zawierać od 3 do 50 znaków.";s:12:"caption_desc";s:1:" ";s:5:"error";s:17:"Zle dane podales!";s:8:"required";s:1:"1";}', 'none', 'integer', 'xvauction_fields_option', 0, -200),
(13, '/', 'pieces', 'none', 'a:21:{s:7:"Caption";s:14:"Ilość sztuk ";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:0:"";s:10:"AddDefault";s:1:"1";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:19:"Liczba sztuk towaru";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:36:"Musisz podać liczbę, chociażby 1.";s:6:"Filter";s:16:"/^([0-9]){1,5}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:13:"Ilość sztuk";s:13:"detail_before";s:1:" ";s:12:"detail_after";s:5:" szt.";}', 'none', 'integer', 'xvauction_fields_int_range', 0, -190),
(14, '/Komputery/Komputery_stacjonarne/', 'ilosc_ram', 'quick', 'a:16:{s:7:"Caption";s:12:"Ilość ram:";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:42:"Liczba może zawierać od 0 do 50 znaków.";s:11:"CaptionDesc";s:11:"Opis tytulu";s:5:"Error";s:27:"Złą ilośc ram podałeś.";s:6:"Filter";s:15:"/^([0-9]){0,}$/";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(15, '/', 'message', 'none', 'a:4:{s:7:"caption";s:27:"Wiadomość dla kupującego";s:10:"input_desc";s:87:"Wiadomość która zostanie wyświetlona i wysłana użytkownikowi, gdy kupi przedmiot.";s:5:"error";s:40:"Zła wiadomość, proszę ją poprawić.";s:14:"show_templates";s:1:"1";}', 'none', 'string', 'xvauction_fields_wysiwyg', 0, 0),
(17, '/', 'shipment', 'none', 'a:12:{s:7:"caption";s:16:"Koszt przesyłki";s:10:"input_desc";s:39:"Tytul moze zawierac od 3 do 50 znaków.";s:12:"caption_desc";s:15:"Koszt przesylki";s:5:"error";s:32:"Musisz wybrać formę przesyłki";s:7:"methods";s:281:"Paczka pocztowa ekonomiczna\r\nPaczka pocztowa priorytetowa\r\nPrzesyłka kurierska\r\nList ekonomiczny\r\nList priorytetowy\r\nList polecony ekonomiczny\r\nList polecony priorytetowy\r\nPrzesyłka pobraniowa\r\nPrzesyłka pobraniowa priorytetowa\r\nPrzesyłka kurierska pobraniowa\r\nOdbiór osobisty";s:7:"column1";s:0:"";s:7:"column2";s:17:"Metoda przesyłki";s:7:"column3";s:14:"Koszt wysyłki";s:7:"column4";s:16:"Dopłata za szt.";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:15:"Koszt przesylki";s:7:"column5";s:15:"Liczba w paczce";}', 'none', 'string', 'xvauction_fields_shipment', 0, 0),
(18, '/', 'location', 'both', 'a:11:{s:7:"caption";s:11:"Lokalizacja";s:13:"quick_caption";s:11:"Lokalizacja";s:17:"input_description";s:42:"Liczba może zawierać od 0 do 50 znaków.";s:19:"caption_description";s:1:" ";s:5:"error";s:18:"Zle podales adres!";s:10:"defaultLat";s:15:"52.173931692568";s:10:"defaultLng";s:13:"18.8525390625";s:8:"required";s:1:"1";s:14:"detail_caption";s:11:"Lokalizacja";s:13:"detail_enable";s:1:"1";s:15:"detail_show_map";s:1:"1";}', 'none', 'string', 'xvauction_fields_geo', 200, 0),
(21, '/', 'premium', 'advanced', 'a:10:{s:7:"caption";s:7:"Premium";s:17:"input_description";s:33:"Opcje premium, które są PŁATNE";s:19:"caption_description";s:1:" ";s:5:"error";s:23:"Źle wypełniłeś pole";s:7:"methods";s:73:"Ogłoszenie na początku listy\r\nPogrubienie\r\nPodświetlenie\r\nNa głównej";s:13:"detail_enable";s:1:"0";s:14:"detail_caption";s:13:"Opcje premium";s:10:"min_select";s:1:"0";s:10:"max_select";s:1:"0";s:13:"quick_caption";s:8:" Premium";}', 'none', 'string', 'xvauction_fields_checkboxs', 0, -300),
(23, '/', 'gallery', 'none', 'a:8:{s:7:"caption";s:7:"Gallery";s:12:"caption_desc";s:19:"Gallery for auction";s:5:"error";s:17:"Zle dane podales!";s:14:"error_filetype";s:56:"Error: Invalid file type! Supported: png, jpg, jpeg, gif";s:12:"error_upload";s:20:"Error: Upload error!";s:9:"drag_here";s:21:"Drag your images here";s:6:"delete";s:6:"Delete";s:7:"preview";s:7:"Preview";}', 'none', 'string', 'xvauction_fields_gallery', 0, 0),
(24, '/Motoryzacja/Motocykle/', 'm_year', 'quick', 'a:21:{s:7:"Caption";s:13:"Rok produkcji";s:6:"Before";s:4:"od  ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" r.";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:1:"4";s:9:"InputDesc";s:79:"Data produkcji samochodu z karty rejestracyjnej. Liczba z przedziału 1900-2012";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:35:"Musisz podać rok produkcji pojazdu";s:6:"Filter";s:16:"/^([0-9]){4,4}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:13:"Rok produkcji";s:13:"detail_before";s:0:"";s:12:"detail_after";s:0:"";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(25, '/Motoryzacja/Motocykle/', 'm_capacity', 'quick', 'a:21:{s:7:"Caption";s:19:"Pojemność silnika";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:4:" cm3";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:19:"Liczba od 0 do 9999";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:34:"Musisz podać pojemność silnika!";s:6:"Filter";s:16:"/^([0-9]){1,4}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:19:"Pojemność silnika";s:13:"detail_before";s:0:"";s:12:"detail_after";s:3:"cm3";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(26, '/Motoryzacja/Motocykle/', 'm_mileage', 'quick', 'a:21:{s:7:"Caption";s:8:"Przebieg";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" km";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:46:"Podaj przebieg swojego samochodu w kilometrach";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:31:"Musisz podać przebieg pojazdu!";s:6:"Filter";s:15:"/^([0-9]){1,}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:8:"Przebieg";s:13:"detail_before";s:0:"";s:12:"detail_after";s:3:" km";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(27, '/Motoryzacja/Motocykle/', 'm_power', 'quick', 'a:21:{s:7:"Caption";s:11:"Moc silnika";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" KM";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:81:"Podaj moc silnika, jaką masz zapisaną w karcie pojazdu, w Koniach Mechanicznych";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:26:"Musisz podać moc silnika!";s:6:"Filter";s:15:"/^([0-9]){1,}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:11:"Moc silnika";s:13:"detail_before";s:0:"";s:12:"detail_after";s:3:" KM";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(28, '/Motoryzacja/Motocykle/', 'm_petrol', 'quick', 'a:10:{s:7:"caption";s:13:"Rodzaj paliwa";s:17:"input_description";s:21:"Wybierz rodzaj paliwa";s:19:"caption_description";s:1:" ";s:5:"error";s:18:"Wybierz chociaż 1";s:7:"methods";s:42:"benzyna\r\nelektryczny\r\nolej napędowy\r\ninny";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:13:"Rodzaj paliwa";s:10:"min_select";s:1:"1";s:10:"max_select";s:1:"0";s:13:"quick_caption";s:13:"Rodzaj paliwa";}', 'none', 'string', 'xvauction_fields_checkboxs', 0, 0),
(29, '/Motoryzacja/Motocykle/', 'm_details', 'quick', 'a:10:{s:7:"caption";s:6:"Detale";s:17:"input_description";s:28:"Wybierz prawidłowe elementy";s:19:"caption_description";s:1:" ";s:5:"error";s:28:"Wybierz odpowiednie elementy";s:7:"methods";s:228:"Bezwypadkowy\r\nUszkodzony\r\nKupiony w salonie\r\nSprowadzony\r\nPierwszy właściciel\r\nZarejestrowany jako zabytek\r\nZarejestrowany w Polsce\r\nGwarancja\r\nABS\r\nWyświetlacz LCD\r\nStreet fighter\r\nAutomatyczna sk. biegów\r\nKosz\r\nTuningowany";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:18:"Detail description";s:10:"min_select";s:1:"0";s:10:"max_select";s:1:"0";s:13:"quick_caption";s:6:"Detale";}', 'none', 'string', 'xvauction_fields_checkboxs', 0, 0),
(30, '/Motoryzacja/Samochody/', 's_year', 'none', 'a:21:{s:7:"Caption";s:13:"Rok produkcji";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:1:" ";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:1:"4";s:9:"InputDesc";s:29:"Podaj rok produkcji samochodu";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:18:"Zły rok produkcji";s:6:"Filter";s:14:"/^([0-9]){4}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:13:"Rok produkcji";s:13:"detail_before";s:0:"";s:12:"detail_after";s:0:"";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(31, '/Motoryzacja/Samochody/', 's_mileage', 'both', 'a:21:{s:7:"Caption";s:8:"Przebieg";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" km";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:35:"Podaj przebieg swojego pojazdu w KM";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:31:"Musisz podać przebieg pojazdu!";s:6:"Filter";s:15:"/^([0-9]){0,}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:8:"Przebieg";s:13:"detail_before";s:1:" ";s:12:"detail_after";s:3:" km";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(32, '/Motoryzacja/Samochody/', 's_capacity', 'both', 'a:21:{s:7:"Caption";s:19:"Pojemność silnika";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:4:" cm3";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:25:"Podaj pojemność silnika";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:19:"Złe podałeś dane";s:6:"Filter";s:15:"/^([0-9]){0,}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:19:"Pojemność silnika";s:13:"detail_before";s:0:"";s:12:"detail_after";s:4:" cm3";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(33, '/Motoryzacja/Samochody/', 's_power', 'both', 'a:21:{s:7:"Caption";s:11:"Moc silnika";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" KM";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:48:"Podaj liczbę koni mechanicznych twojego pojazdu";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:20:"Złe podałeś dane!";s:6:"Filter";s:15:"/^([0-9]){0,}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:11:"Moc silnika";s:13:"detail_before";s:0:"";s:12:"detail_after";s:3:" KM";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0),
(34, '/Motoryzacja/Samochody/', 's_addons', 'both', 'a:10:{s:7:"caption";s:7:"Dodatki";s:17:"input_description";s:48:"Wybierz elementy, które twój samochód posiada";s:19:"caption_description";s:7:"Dodatki";s:5:"error";s:16:"Zaznacz elementy";s:7:"methods";s:87:"Radio\r\nTelewizor\r\nKomputer\r\nABS\r\nAutom. skrz. biegów\r\nESP\r\nACC\r\nAFIL\r\nAFL\r\nN20\r\nOC\r\nAC";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:7:"Dodatki";s:10:"min_select";s:1:"0";s:10:"max_select";s:1:"0";s:13:"quick_caption";s:7:"Dodatki";}', 'none', 'string', 'xvauction_fields_checkboxs', 0, 0),
(36, '/Komputery/Laptopy/', 'lap_ram', 'both', 'a:21:{s:7:"Caption";s:11:"Ilość RAM";s:6:"Before";s:3:"od ";s:6:"Center";s:3:"do ";s:5:"After";s:3:" MB";s:10:"AddDefault";s:0:"";s:20:"QuickLabelFirstStyle";s:12:"width: 64px;";s:21:"QuickLabelSecondStyle";s:12:"width: 64px;";s:20:"QuickInputFirstStyle";s:12:"width: 64px;";s:21:"QuickInputSecondStyle";s:12:"width: 64px;";s:18:"AdvancedInputStyle";s:12:"width: 64px;";s:16:"AdvancedAferText";s:0:"";s:18:"AdvancedLabelStyle";s:12:"width: 64px;";s:9:"maxlength";s:3:"250";s:9:"InputDesc";s:40:"Proszę podać ilość pamięci RAM w MB";s:11:"CaptionDesc";s:1:" ";s:5:"Error";s:29:"Źłą podałeś ilość RAM!";s:6:"Filter";s:17:"/^([0-9]){1,10}$/";s:13:"detail_enable";s:1:"1";s:14:"detail_caption";s:12:"Pamięć RAM";s:13:"detail_before";s:0:"";s:12:"detail_after";s:3:" MB";}', 'none', 'integer', 'xvauction_fields_int_range', 0, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
